### ISSUE TITLE
int null

### ISSUE THREAD

**Issue by SergeyMar** [Rawrfuls/ThePunisher#2]
I have not obtained to make INT NULL he changed to INT (11) NULL DEFAULT NULL.What should I do

**Comment by Gigawiz** [comment]
I'm not following what you mean

**Comment by SergeyMar** [comment]
CREATE TABLE `chatbans` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`steamId` VARCHAR(32) NOT NULL,
	`admin` VARCHAR(32) NOT NULL,
	`banMessage` VARCHAR(512) NULL DEFAULT NULL,
	`charactername` VARCHAR(255) NULL DEFAULT NULL,
	`banDuration` INT(11) NULL DEFAULT NULL,
	`banTime` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
	INDEX `Индекс 1` (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=5
;

**Comment by SergeyMar** [comment]
How to configure MYsql

**Comment by Gigawiz** [comment]
you fill in the database details in ThePunisher.Configuration.xml, then on next reload/reboot The Punisher will connect to MySql and create the required tables

**Comment by Gigawiz** [comment]
Closing due to lack of response.
