### ISSUE TITLE
Not Loaded

### ISSUE THREAD

**Issue by stilesa** [Rawrfuls/ThePunisher#4]
Plugin is throwing this error when rocket attempts to load

ThePunisher >> The Punisher has been loaded!
Failed to load ThePunisher, unloading now... :System.NullReferenceException: Object reference not set to an instance of an object
  at rawrfuls.ThePunisher.ThePunisher.Load () [0x00000] in <filename unknown>:0
  at Rocket.Core.Plugins.RocketPlugin.LoadPlugin () [0x00000] in <filename unknown>:0
                                                                                      [unloading] ThePunisher

unturned 3.17.5.1
rocket 1065

**Comment by JustOneMoreBlock** [comment]
Loads, but has issues #7 - You could probably close this now.
